# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshbuddy" do
  name "sshbuddy"
  desc "A modern terminal interface for managing SSH connections"
  homepage "https://github.com/javedh-dev/sshbuddy"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshbuddy"
  bash_completion "completions/sshbuddy.bash"
  zsh_completion "completions/sshbuddy.zsh"
  fish_completion "completions/sshbuddy.fish"

  on_macos do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_x86_64.tar.gz"
      sha256 "dde0aac055c47e033573b300840846fccd32db6bc264a6a84c60113fb057c433"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_arm64.tar.gz"
      sha256 "8f6df85bcdf644a6b7d2b09a7464448bb281dd3d735afe306c61a261bc26c6ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_x86_64.tar.gz"
      sha256 "3d6125d03771dd02c7cb05f08e07a8a521258fa22064b7890558f8a32510297e"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_arm64.tar.gz"
      sha256 "aa293a586bdbc1fbf4777a04eae005eaf5470316df2dd8bc4b94bd78124f5be6"
    end
  end

  # No zap stanza required
end
