# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshbuddy" do
  name "sshbuddy"
  desc "A modern terminal interface for managing SSH connections"
  homepage "https://github.com/javedh-dev/sshbuddy"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshbuddy"
  bash_completion "completions/sshbuddy.bash"
  zsh_completion "completions/sshbuddy.zsh"
  fish_completion "completions/sshbuddy.fish"

  on_macos do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_x86_64.tar.gz"
      sha256 "5e519d94271557a46d4127a96fb79912087534434e74810dbc2528da018a20de"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_arm64.tar.gz"
      sha256 "6398faf644ae877b3cbf1ebb14471d222437336c41a2191baacbbf3aac98d3e6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_x86_64.tar.gz"
      sha256 "998c24ab2691a7e0c7531ef8cebd985369c03e4a01da7fd518ac9bdfeb8affdf"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_arm64.tar.gz"
      sha256 "7f22c286dcb1d1cfc789c09d92709a8af15af71feabac982b897eab7cb5e234c"
    end
  end

  # No zap stanza required
end
