# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshbuddy" do
  name "sshbuddy"
  desc "A modern terminal interface for managing SSH connections"
  homepage "https://github.com/javedh-dev/sshbuddy"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshbuddy"
  bash_completion "completions/sshbuddy.bash"
  zsh_completion "completions/sshbuddy.zsh"
  fish_completion "completions/sshbuddy.fish"

  on_macos do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_x86_64.tar.gz"
      sha256 "5f7a86edec5a42d2b108c7d123e31ab75322cf38de556547b4cc68e17d82cdd5"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_arm64.tar.gz"
      sha256 "53307d649aaebe6cd080fd9f78273872b76901079861098b414eb1726cd9c614"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_x86_64.tar.gz"
      sha256 "2feb756295617197a174c00dd76045f31bb9b03b96ba0132601d5055e63c6b2c"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_arm64.tar.gz"
      sha256 "23d24dd2a895a0de3e5e2a99d23a18283646e62142a51ae3ab268e0e26ad07b1"
    end
  end

  # No zap stanza required
end
