# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshbuddy" do
  name "sshbuddy"
  desc "A modern terminal interface for managing SSH connections"
  homepage "https://github.com/javedh-dev/sshbuddy"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshbuddy"
  bash_completion "completions/sshbuddy.bash"
  zsh_completion "completions/sshbuddy.zsh"
  fish_completion "completions/sshbuddy.fish"

  on_macos do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_x86_64.tar.gz"
      sha256 "77457fb67fb75f774df6e0da5758a079fed8ba21e0ae3a6836d56407a1ac40c8"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Darwin_arm64.tar.gz"
      sha256 "282b95c06fbc46fe56aba2e490a0402511e08efe19321966b37f0b034deb5760"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_x86_64.tar.gz"
      sha256 "8f42840079f54344500ed3c6d5d2f7b145d9837010421e8aaaeb7931dc303994"
    end
    on_arm do
      url "https://github.com/javedh-dev/sshbuddy/releases/download/v#{version}/sshbuddy_Linux_arm64.tar.gz"
      sha256 "29845370d75fa277b25355dc3132ec35db5351abb64b64d4312d9e4b02b9ea01"
    end
  end

  # No zap stanza required
end
