# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshbuddy < Formula
  desc "A beautiful TUI app to manage SSH connections"
  homepage "https://github.com/javedh-dev/sshbuddy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/javedh-dev/sshuddy/releases/download/v0.1.0/sshuddy_Darwin_x86_64.tar.gz"
      sha256 "928be70765fac1bcc49ee8e236172d2fadfd21b290b03c7f4785e57fbc3614d1"

      def install
        bin.install "sshbuddy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/javedh-dev/sshuddy/releases/download/v0.1.0/sshuddy_Darwin_arm64.tar.gz"
      sha256 "034114610abd0d00b6bf98d35eac7f2de92f9863fad7869e258d7e1a2a0bcc74"

      def install
        bin.install "sshbuddy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/javedh-dev/sshuddy/releases/download/v0.1.0/sshuddy_Linux_x86_64.tar.gz"
      sha256 "6175111f82fa7ab849c642aac448701bb1eda2cde3ac093951377a5e214b43bf"
      def install
        bin.install "sshbuddy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javedh-dev/sshuddy/releases/download/v0.1.0/sshuddy_Linux_arm64.tar.gz"
      sha256 "76227ad42d73aa7e6cdfc6e504b5a8abf4ea7da83ddf7b74af3f2dd921f70e70"
      def install
        bin.install "sshbuddy"
      end
    end
  end

  test do
    system "#{bin}/sshbuddy", "--version"
  end
end
